pipeline:
  install:
    image: node:7.6.0
    commands:
      - yarn install
  build:
    image: node:7.6.0
    commands:
      - npm run build
  lint:
    image: node:7.6.0
    commands:
      - npm run lint
