cache:
  mount:
    - node_modules
    - .git

pipeline:
  install:
    image: node:7.6.0
    commands:
      - yarn install
      - npm rebuild node-sass
  build:
    image: node:7.6.0
    commands:
      - yarn run build
  lint:
    image: node:7.6.0
    commands:
      - yarn run lint
