sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.5
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
- npm run build
script: npm run test-ci
deploy:
  matrix:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: FILE TO UPLOAD
    skip_cleanup: true
    on:
      tags: true
      branch: maste
  - provider: pages
    skip_cleanup: true
    local_dir: www
    github_token: $GITHUB_TOKEN
    on:
      branch: master
